// flow-typed signature: 0cd1d2d4b52fc264afe3f6e0f9761fee
// flow-typed version: <<STUB>>/webpack-cdn-plugin_v^2.2.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-cdn-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-cdn-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-cdn-plugin/main' {
  declare module.exports: any;
}

declare module 'webpack-cdn-plugin/module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-cdn-plugin/main.js' {
  declare module.exports: $Exports<'webpack-cdn-plugin/main'>;
}
declare module 'webpack-cdn-plugin/module.js' {
  declare module.exports: $Exports<'webpack-cdn-plugin/module'>;
}
